import typing

from ._http import HTTPRefreshProcessor

class FormNotFoundError(Exception): ...

class Readable(str):
    def read(self) -> None: ...

class FoundLink:
    @property
    def absolute_url(self) -> str: ...

class Browser:
    def set_handle_robots(self, flag: bool) -> None: ...
    def set_handle_redirect(self, flag: bool) -> None: ...
    def set_handle_refresh(
        self, processor: HTTPRefreshProcessor, max_time: int, honor_time: bool
    ) -> None: ...
    def set_ca_data(self, cafile: str) -> None: ...
    def open(self, url: str) -> Readable: ...
    def select_form(self, predicate: typing.Any) -> None: ...
    def set_value(self, value: str, name: str) -> None: ...
    def submit(self) -> Readable: ...
    def follow_link(self, text: str) -> str: ...
    def find_link(self, text: str) -> FoundLink: ...
