name: build_site

on:
  push:
    branches:
    - "main"

    paths-ignore:
      - '.github/workflows/run_tests.yml'
      - '.github/dependabot.yml'
      - 'dev_requirements.in'
      - 'dev_requirements.txt'
      - 'tests/**'

  schedule:
    - cron: "30 7 * * *"

jobs:
  build:
    name: Build the website
    runs-on: self-hosted
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - name: "Install Python dependencies"
        run: |
          python3 -m venv .venv
          source .venv/bin/activate

          python3 -m pip install -e .
          python3 -m pip install -r requirements.txt

      - name: "Get the book data"
        if: github.ref == 'refs/heads/main'
        run: |
          source .venv/bin/activate
          python3 get_book_data.py
        env:
          LIBRARY_CARD_NUMBER: ${{ secrets.LIBRARY_CARD_NUMBER }}
          LIBRARY_CARD_PASSWORD: ${{ secrets.LIBRARY_CARD_PASSWORD }}

      - name: "Render the data as HTML"
        run: |
          source .venv/bin/activate
          python3 render_data_as_html.py

      - name: Copy to the public directory
        if: github.ref == 'refs/heads/main'
        run: |
          rsync \
            --compress \
            --recursive \
            --delete \
            --verbose \
            --checksum \
            --exclude="" \
            --include="" \
            --filter="" \
            _html/ \
            ~/repos/alexwlchan.net/_site/my-tools/library-lookup/
