name: run_tests

on:
  push:
    branches:
    - "main"

  pull_request:
    branches:
    - "main"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: dev_requirements.txt

      - name: "Install dependencies"
        run: python3 -m pip install -r dev_requirements.txt

      - name: Check formatting
        run: |
          ruff check .
          ruff format --check .

      - name: Check docstrings
        run: interrogate -vv

      - name: Check types
        run: mypy *.py src tests

      - name: Run tests
        run: |
          coverage run -m pytest tests
          coverage report --show-missing --skip-covered
